<a href="https://colab.research.google.com/github/Sumanth-Raj-Analyst/skills-introduction-to-github/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

1. Create Series: syntax: pd.series(var/col)

In [ ]:
sr=pd.Series([10,12.5,3+4j,True,{12,15},{"Name":"Tony Stark"}])
sr[4]=89.5
sr[5]="Iron Man"
type(sr)
sr

0          10
1        12.5
2      (3+4j)
3        True
4        89.5
5    Iron Man
dtype: object

#Creating DataFrame:

In [3]:

df = pd.DataFrame({"SName": ["A", "B", "C", "D"], "Sid": [10, 12, 15, 16], "Marks": [90, 95, 88, 85]})

print(df)

print(df["SName"])

print(df.iloc[1, df.columns.get_loc("SName")])

df.iloc[2, df.columns.get_loc("SName")] = "E"

print(df)

  SName  Sid  Marks
0     A   10     90
1     B   12     95
2     C   15     88
3     D   16     85
0    A
1    B
2    C
3    D
Name: SName, dtype: object
B
  SName  Sid  Marks
0     A   10     90
1     B   12     95
2     E   15     88
3     D   16     85

2. Add new Column:

In [ ]:
df2=pd.read_csv("Titanic-Dataset (1).csv")
df3=pd.read_csv("amazon_fires (2).csv", encoding="ISO-8859-1")

df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df2.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df2.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df2.shape

(891, 12)

In [ ]:
df2.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df2["Pclass"].unique()

array([3, 1, 2])

In [ ]:
df2["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
df2.to_csv("Titanic-Dataset.csv")

In [ ]:
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
#df2["Name"][0:3]

df2["Name"][-5:]

886                       Montvila, Rev. Juozas
887                Graham, Miss. Margaret Edith
888    Johnston, Miss. Catherine Helen "Carrie"
889                       Behr, Mr. Karl Howell
890                         Dooley, Mr. Patrick
Name: Name, dtype: object

In [ ]:
df2.loc[0:5:1,["Name","Sex"]]

                                                Name     Sex
0                            Braund, Mr. Owen Harris    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                             Heikkinen, Miss. Laina  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                           Allen, Mr. William Henry    male
5                                   Moran, Mr. James    male

In [ ]:
df2.head()

df2.iloc[0:3:1,3:5:1]

                                                Name     Sex
0                            Braund, Mr. Owen Harris    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                             Heikkinen, Miss. Laina  female

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

#BOOLEAN FILTERING:

In [ ]:
df2[df2['Sex']=="female"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
df2[df2["Survived"]==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
df2[(df2["Age"]>60) & (df2["Survived"]==1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN

In [ ]:
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df2[(df2["Pclass"]==3) & (df2["Sex"]=="male") & (df2["Age"]<=25)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
37,38,0,3,"Cann, Mr. Ernest Charles",male,21.0,0,0,A./5. 2152,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.0,4,2,347082,31.2750,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S

In [ ]:
df2[(df2["SibSp"]>=1) & (df2["Parch"]>=1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
df2[(df2["SibSp"]==1) | (df2["Parch"]==1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
df2[df2["Age"].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
df2[df2["Age"].notnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

#Data Cleaning:

In [ ]:
df3.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

1. Renaming the columns:

In [ ]:
d={"ano":"Year","mes":"Month","estado":"State","numero":"No of Fires","encontro":"Date"}
df3.rename(columns={"Janeiro":"january","ano":"Year","mes":"Month","estado":"State","numero":"No of Fires","encontro":"Date"},inplace=True)
df3

      Year     Month      State No of Fires      Date
0     1998   Janeiro       Acre     0 Fires  1/1/1998
1     1999   Janeiro       Acre     0 Fires  1/1/1999
2     2000   Janeiro       Acre     0 Fires  1/1/2000
3     2001   Janeiro       Acre     0 Fires  1/1/2001
4     2002   Janeiro       Acre     0 Fires  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  Dezembro  Tocantins         128  1/1/2012
6450  2013  Dezembro  Tocantins          85  1/1/2013
6451  2014  Dezembro  Tocantins         223  1/1/2014
6452  2015  Dezembro  Tocantins         373  1/1/2015
6453  2016  Dezembro  Tocantins         119  1/1/2016

[6454 rows x 5 columns]

In [ ]:
df3.drop_duplicates(inplace=True)
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Year         6424 non-null   int64
 1   Month        6424 non-null   object
 2   State        6424 non-null   object
 3   No of Fires  6292 non-null   object
 4   Date         6424 non-null   object
dtypes: int64(1), object(4)
memory usage: 301.1+ KB

In [ ]:
df3.head()

   Year    Month State No of Fires      Date
0  1998  Janeiro  Acre     0 Fires  1/1/1998
1  1999  Janeiro  Acre     0 Fires  1/1/1999
2  2000  Janeiro  Acre     0 Fires  1/1/2000
3  2001  Janeiro  Acre     0 Fires  1/1/2001
4  2002  Janeiro  Acre     0 Fires  1/1/2002

In [ ]:
df3["Month"].unique()

array(['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho',
       'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

In [ ]:
d={"Janeiro":"Jan",'Fevereiro':'Fevereiro', 'Março':'Março', 'Abril':'Abril', 'Maio':'Maio', 'Junho':'Junho', 'Julho':'Julho',
       'Agosto':'Agosto', 'Setembro':'Setembro', 'Outubro':'Outubro', 'Novembro':'Novembro', 'Dezembro':'Dezembro'}

df3["Month"]=df3["Month"].map(d)

4. Removing unwanted Data from columns:

In [ ]:

df3["No of Fires"]=df3["No of Fires"].str.strip("Fires")
df3.head(10)

   Year Month State No of Fires      Date
0  1998   Jan  Acre          0   1/1/1998
1  1999   Jan  Acre          0   1/1/1999
2  2000   Jan  Acre          0   1/1/2000
3  2001   Jan  Acre          0   1/1/2001
4  2002   Jan  Acre          0   1/1/2002
5  2003   Jan  Acre         10   1/1/2003
6  2004   Jan  Acre          0   1/1/2004
7  2005   Jan  Acre         12   1/1/2005
8  2006   Jan  Acre          4   1/1/2006
9  2007   Jan  Acre          0   1/1/2007

5. Applying in-built functions on columns:

In [ ]:
df3["Month"]=df3["Month"].str.capitalize()
df3.head()

   Year Month State No of Fires      Date
0  1998   Jan  Acre          0   1/1/1998
1  1999   Jan  Acre          0   1/1/1999
2  2000   Jan  Acre          0   1/1/2000
3  2001   Jan  Acre          0   1/1/2001
4  2002   Jan  Acre          0   1/1/2002

6. Handling Missing Values:

In [ ]:
#df3.dropna()
#df3.info()

In [ ]:
df3.head()
type(df3["No of Fires"][1])

df3["No of Fires"]=pd.to_numeric(df3["No of Fires"])
type(df3["No of Fires"][1])
avg=df3["No of Fires"].mean()
avg

df3["No of Fires"]=df3["No of Fires"].fillna(avg)


# df3["No of Fires"]=df3["No of Fires"].fillna(avg)
# df3["No of Fires"].mean()

In [ ]:
df3["No of Fires"].fillna(method='backfill')
df3["No of Fires"].fillna(method='ffill')

<ipython-input-179-e93c436c233f>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3["No of Fires"].fillna(method='backfill')
<ipython-input-179-e93c436c233f>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3["No of Fires"].fillna(method='ffill')

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
6449    128.0
6450     85.0
6451    223.0
6452    373.0
6453    119.0
Name: No of Fires, Length: 6424, dtype: float64

In [ ]:
df3["No of Fires"]=df3["No of Fires"].astype(int)
df3.head()

   Year Month State  No of Fires      Date
0  1998   Jan  Acre            0  1/1/1998
1  1999   Jan  Acre            0  1/1/1999
2  2000   Jan  Acre            0  1/1/2000
3  2001   Jan  Acre            0  1/1/2001
4  2002   Jan  Acre            0  1/1/2002

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Year         6424 non-null   int64
 1   Month        6424 non-null   object
 2   State        6424 non-null   object
 3   No of Fires  6424 non-null   int64
 4   Date         6424 non-null   object
dtypes: int64(2), object(3)
memory usage: 559.2+ KB

In [ ]:
new=[4,0,1,2,3]
df3=df3[df3.columns[new]]

df3.head()

       Date  Year Month State  No of Fires
0  1/1/1998  1998   Jan  Acre            0
1  1/1/1999  1999   Jan  Acre            0
2  1/1/2000  2000   Jan  Acre            0
3  1/1/2001  2001   Jan  Acre            0
4  1/1/2002  2002   Jan  Acre            0

In [ ]:
df3["Month"]=df3["Month"].str.replace("Janeiro","January")
df3

          Date  Year     Month      State  No of Fires
0     1/1/1998  1998       Jan       Acre            0
1     1/1/1999  1999       Jan       Acre            0
2     1/1/2000  2000       Jan       Acre            0
3     1/1/2001  2001       Jan       Acre            0
4     1/1/2002  2002       Jan       Acre            0
...        ...   ...       ...        ...          ...
6449  1/1/2012  2012  Dezembro  Tocantins          128
6450  1/1/2013  2013  Dezembro  Tocantins           85
6451  1/1/2014  2014  Dezembro  Tocantins          223
6452  1/1/2015  2015  Dezembro  Tocantins          373
6453  1/1/2016  2016  Dezembro  Tocantins          119

[6424 rows x 5 columns]

In [ ]:
df3.drop('Date',axis=1)

      Year     Month      State  No of Fires
0     1998       Jan       Acre            0
1     1999       Jan       Acre            0
2     2000       Jan       Acre            0
3     2001       Jan       Acre            0
4     2002       Jan       Acre            0
...    ...       ...        ...          ...
6449  2012  Dezembro  Tocantins          128
6450  2013  Dezembro  Tocantins           85
6451  2014  Dezembro  Tocantins          223
6452  2015  Dezembro  Tocantins          373
6453  2016  Dezembro  Tocantins          119

[6424 rows x 4 columns]

In [ ]:
df3.drop(df3.index[0:10:1])

          Date  Year     Month      State  No of Fires
10    1/1/2008  2008       Jan       Acre            0
11    1/1/2009  2009       Jan       Acre            0
12    1/1/2010  2010       Jan       Acre            1
13    1/1/2011  2011       Jan       Acre            0
14    1/1/2012  2012       Jan       Acre            0
...        ...   ...       ...        ...          ...
6449  1/1/2012  2012  Dezembro  Tocantins          128
6450  1/1/2013  2013  Dezembro  Tocantins           85
6451  1/1/2014  2014  Dezembro  Tocantins          223
6452  1/1/2015  2015  Dezembro  Tocantins          373
6453  1/1/2016  2016  Dezembro  Tocantins          119

[6414 rows x 5 columns]

In [ ]:
df3.reset_index()

# df3.drop("index",axis=1,inplace=True)

df3.set_index("Year")

          Date     Month      State  No of Fires
Year
1998  1/1/1998       Jan       Acre            0
1999  1/1/1999       Jan       Acre            0
2000  1/1/2000       Jan       Acre            0
2001  1/1/2001       Jan       Acre            0
2002  1/1/2002       Jan       Acre            0
...        ...       ...        ...          ...
2012  1/1/2012  Dezembro  Tocantins          128
2013  1/1/2013  Dezembro  Tocantins           85
2014  1/1/2014  Dezembro  Tocantins          223
2015  1/1/2015  Dezembro  Tocantins          373
2016  1/1/2016  Dezembro  Tocantins          119

[6424 rows x 4 columns]

#Group By Operations:

In [ ]:
df4=pd.read_csv("https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/hr_data.csv")
df4.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [ ]:
gp=df4.groupby("department")
gp

gp.groups

{'IT': [61, 62, 63, 64, 65, 70, 138, 139, 140, 141, 142, 147, 214, 215, 216, 217, 218, 223, 291, 292, 293, 294, 295, 300, 367, 368, 369, 370, 371, 376, 443, 444, 445, 446, 447, 452, 519, 520, 521, 522, 523, 528, 595, 596, 597, 598, 599, 604, 671, 672, 673, 674, 675, 680, 747, 748, 749, 750, 751, 756, 823, 824, 825, 826, 827, 832, 899, 900, 901, 902, 903, 908, 975, 976, 977, 978, 979, 984, 1051, 1052, 1053, 1054, 1055, 1060, 1127, 1128, 1129, 1130, 1131, 1136, 1204, 1205, 1206, 1207, 1208, 1213, 1214, 1215, 1216, 1281, ...], 'RandD': [301, 302, 303, 304, 305, 453, 454, 455, 456, 457, 605, 606, 607, 608, 609, 833, 834, 835, 836, 837, 985, 986, 987, 988, 989, 1061, 1062, 1063, 1064, 1065, 1217, 1218, 1219, 1291, 1292, 1293, 1294, 1295, 1296, 1368, 1369, 1370, 1371, 1372, 1373, 1445, 1446, 1447, 1448, 1449, 1450, 1522, 1523, 1524, 1525, 1526, 1598, 1599, 1600, 1601, 1602, 1675, 1676, 1677, 1678, 1679, 1751, 1752, 1753, 1754, 1755, 1827, 1828, 1829, 1830, 1831, 1903, 1904, 1905, 1906, 1907, 1979, 1980, 1981, 1982, 1983, 2055, 2056, 2057, 2058, 2059, 2131, 2132, 2133, 2134, 2135, 2207, 2208, 2209, 2210, ...], 'accounting': [28, 29, 30, 79, 105, 106, 107, 155, 181, 182, 183, 224, 225, 232, 258, 259, 260, 308, 334, 335, 336, 377, 378, 384, 410, 411, 412, 460, 486, 487, 488, 529, 530, 536, 562, 563, 564, 612, 638, 639, 640, 688, 714, 715, 716, 764, 790, 791, 792, 840, 866, 867, 868, 916, 942, 943, 944, 992, 1018, 1019, 1020, 1068, 1094, 1095, 1096, 1145, 1171, 1172, 1173, 1222, 1248, 1249, 1250, 1299, 1325, 1326, 1327, 1376, 1402, 1403, 1404, 1453, 1479, 1480, 1481, 1529, 1555, 1556, 1557, 1606, 1632, 1633, 1634, 1682, 1708, 1709, 1710, 1758, 1784, 1785, ...], 'hr': [31, 32, 33, 34, 108, 109, 110, 111, 184, 185, 186, 187, 226, 227, 228, 261, 262, 263, 264, 337, 338, 339, 340, 379, 380, 381, 413, 414, 415, 416, 489, 490, 491, 492, 531, 532, 533, 565, 566, 567, 568, 641, 642, 643, 644, 717, 718, 719, 720, 793, 794, 795, 796, 869, 870, 871, 872, 945, 946, 947, 948, 1021, 1022, 1023, 1024, 1097, 1098, 1099, 1100, 1174, 1175, 1176, 1177, 1251, 1252, 1253, 1254, 1328, 1329, 1330, 1331, 1405, 1406, 1407, 1408, 1482, 1483, 1484, 1485, 1558, 1559, 1560, 1561, 1635, 1636, 1637, 1638, 1711, 1712, 1713, ...], 'management': [60, 82, 137, 158, 213, 235, 290, 311, 366, 387, 442, 463, 518, 539, 594, 615, 670, 691, 746, 767, 822, 843, 898, 919, 974, 995, 1050, 1071, 1126, 1148, 1203, 1225, 1280, 1302, 1357, 1379, 1434, 1456, 1511, 1532, 1587, 1609, 1664, 1685, 1740, 1761, 1816, 1837, 1892, 1913, 1968, 1989, 2044, 2065, 2120, 2141, 2196, 2217, 2272, 2293, 2348, 2369, 2424, 2445, 2500, 2522, 2577, 2599, 2654, 2676, 2731, 2753, 2808, 2830, 2885, 2906, 2961, 2983, 3038, 3059, 3114, 3135, 3190, 3211, 3266, 3287, 3342, 3363, 3418, 3439, 3494, 3515, 3570, 3591, 3646, 3667, 3722, 3743, 3798, 3819, ...], 'marketing': [77, 83, 84, 85, 148, 149, 150, 151, 152, 153, 159, 160, 161, 229, 230, 236, 237, 238, 306, 312, 313, 314, 382, 388, 389, 390, 458, 464, 465, 466, 534, 540, 541, 542, 610, 616, 617, 618, 686, 692, 693, 694, 762, 768, 769, 770, 838, 844, 845, 846, 914, 920, 921, 922, 990, 996, 997, 998, 1066, 1072, 1073, 1074, 1142, 1143, 1149, 1150, 1151, 1220, 1226, 1227, 1228, 1297, 1303, 1304, 1305, 1374, 1380, 1381, 1382, 1451, 1457, 1458, 1459, 1527, 1533, 1534, 1535, 1603, 1604, 1610, 1611, 1612, 1680, 1686, 1687, 1688, 1756, 1762, 1763, 1764, ...], 'product_mng': [66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 143, 144, 145, 146, 219, 220, 221, 222, 296, 297, 298, 299, 372, 373, 374, 375, 448, 449, 450, 451, 524, 525, 526, 527, 600, 601, 602, 603, 676, 677, 678, 679, 752, 753, 754, 755, 828, 829, 830, 831, 904, 905, 906, 907, 980, 981, 982, 983, 1056, 1057, 1058, 1059, 1132, 1133, 1134, 1135, 1209, 1210, 1211, 1212, 1286, 1287, 1288, 1289, 1363, 1364, 1365, 1366, 1440, 1441, 1442, 1443, 1517, 1518, 1519, 1520, 1593, 1594, 1595, 1596, 1670, 1671, 1672, 1673, 1746, 1747, 1748, 1749, 1822, 1823, ...], 'sales': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 78, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 154, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 231, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 307, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, ...], 'support': [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 80, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 156, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 233, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 309, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 385, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 461, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 537, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 613, 656, 657, 658, 659, ...], 'technical': [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 57, 58, 59, 81, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 134, 135, 136, 157, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 210, 211, 212, 234, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 287, 288, 289, 310, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 363, 364, 365, 386, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 439, 440, 441, 462, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, ...]}

In [ ]:
ac=gp.get_group("accounting")

# ac["number_project"].sum()
# sum(ac["number_project"])

it=gp.get_group("IT")

it[it["promotion_last_5years"]==1].count()

employee_id              3
number_project           3
average_montly_hours     3
time_spend_company       3
Work_accident            3
left                     3
promotion_last_5years    3
department               3
salary                   3
dtype: int64

In [ ]:
df4["salary"]=df4["salary"].str.replace("medium","50,000")
df4["salary"]=df4["salary"].str.replace("low","20,000")
df4["salary"]=df4["salary"].str.replace("high","70,000")

df4

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,"20,000"
1,1005,5,262,6,0,1,0,sales,"50,000"
2,1486,7,272,4,0,1,0,sales,"50,000"
3,1038,5,223,5,0,1,0,sales,"20,000"
4,1057,2,159,3,0,1,0,sales,"20,000"
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,"20,000"
14995,87673,2,160,3,0,1,0,support,"20,000"
14996,87679,2,143,3,0,1,0,support,"20,000"
14997,87681,6,280,4,0,1,0,support,"20,000"
14998,87684,2,158,3,0,1,0,support,"20,000"

In [ ]:
df4["salary"]=df4["salary"].str.replace(',','')
df4.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,20000
1,1005,5,262,6,0,1,0,sales,50000
2,1486,7,272,4,0,1,0,sales,50000
3,1038,5,223,5,0,1,0,sales,20000
4,1057,2,159,3,0,1,0,sales,20000

In [ ]:
df4["salary"]=pd.to_numeric(df4["salary"])

In [ ]:
gp["salary"].mean()

department
IT             36462.917685
RandD          37420.584498
accounting     37926.988266
hr             37618.403248
management     48571.428571
marketing      37808.857809
product_mng    36507.760532
sales          36089.371981
support        35841.184388
technical      36345.588235
Name: salary, dtype: float64

In [ ]:
IT=gp.get_group("IT")
IT[IT["promotion_last_5years"]==0].count()

employee_id              1224
number_project           1224
average_montly_hours     1224
time_spend_company       1224
Work_accident            1224
left                     1224
promotion_last_5years    1224
department               1224
salary                   1224
dtype: int64

In [ ]:
D1={"ENAME":["A","B","C","D"],"EID":[1,2,3,4],"DEPT_NO":[10,11,12,13]}
df1=pd.DataFrame(D1)
D2={"MGN_NO":[12,14,15,16],"DEPTNAME":["DEV","TEST","DB","ANALYST"]}
df2=pd.DataFrame(D2)
print("Horizontal Concatination")
df=pd.concat([df1,df2],axis=1)
print(pd.concat([df1,df2],axis=1))
print()
print("Vertical Concatination")
dff=pd.concat([df1,df2],axis=0)
print(pd.concat([df1,df2],axis=0))


df["DEPT_NO"]
dff["DEPT_NO"]

Horizontal Concatination
  ENAME  EID  DEPT_NO  MGN_NO DEPTNAME
0     A    1       10      12      DEV
1     B    2       11      14     TEST
2     C    3       12      15       DB
3     D    4       13      16  ANALYST

Vertical Concatination
  ENAME  EID  DEPT_NO  MGN_NO DEPTNAME
0     A  1.0     10.0     NaN      NaN
1     B  2.0     11.0     NaN      NaN
2     C  3.0     12.0     NaN      NaN
3     D  4.0     13.0     NaN      NaN
0   NaN  NaN      NaN    12.0      DEV
1   NaN  NaN      NaN    14.0     TEST
2   NaN  NaN      NaN    15.0       DB
3   NaN  NaN      NaN    16.0  ANALYST

0    10.0
1    11.0
2    12.0
3    13.0
0     NaN
1     NaN
2     NaN
3     NaN
Name: DEPT_NO, dtype: float64

#Joins:

1. Inner Join

In [ ]:
D1={"ENAME":["A","B","C","D"],"EID":[1,2,3,4],"DEPT_NO":[10,11,11,13]}
df1=pd.DataFrame(D1)
D2={"DEPT_NO":[11,13,13,14],"DEPTNAME":["DEV","DB","DB","ANALYST"]}
df2=pd.DataFrame(D2)

a=pd.merge(df1,df2,on="DEPT_NO",how="inner")
a
a.drop_duplicates()

  ENAME  EID  DEPT_NO DEPTNAME
0     B    2       11      DEV
1     C    3       11      DEV
2     D    4       13       DB

In [ ]:
D1={"ENAME":["A","B","C","D"],"EID":[10,12,25,40],"DEPT_NO":[1,2,2,3]}
df1=pd.DataFrame(D1)
D2={"DEPT_NO":[2,3],"DEPTNAME":["DEV","DB"]}
df2=pd.DataFrame(D2)

b=pd.merge(df1,df2,on="DEPT_NO",how="left")
b

  ENAME  EID  DEPT_NO DEPTNAME
0     A   10        1      NaN
1     B   12        2      DEV
2     C   25        2      DEV
3     D   40        3       DB

3. Right Join:

In [ ]:
D1={"ENAME":["A","B","C","D"],"EID":[10,12,25,40],"DEPT_NO":[1,2,2,3]}
df1=pd.DataFrame(D1)
D2={"DEPT_NO":[2,3,3,4],"DEPTNAME":["DEV","DB","ANALYST","TESTING"]}
df2=pd.DataFrame(D2)

pd.merge(df1,df2,on="DEPT_NO",how="right")

  ENAME   EID  DEPT_NO DEPTNAME
0     B  12.0        2      DEV
1     C  25.0        2      DEV
2     D  40.0        3       DB
3     D  40.0        3  ANALYST
4   NaN   NaN        4  TESTING

4. Outer Join:

In [ ]:
D1={"ENAME":["A","B","C","D"],"EID":[10,12,25,40],"DEPT_NO":[1,2,3,4]}
df1=pd.DataFrame(D1)
D2={"DEPT_NO":[3,4,7,8],"DEPTNAME":["DEV","DB","ANALYST","TESTING"]}
df2=pd.DataFrame(D2)

pd.merge(df1,df2,on="DEPT_NO",how="outer")

  ENAME   EID  DEPT_NO DEPTNAME
0     A  10.0        1      NaN
1     B  12.0        2      NaN
2     C  25.0        3      DEV
3     D  40.0        4       DB
4   NaN   NaN        7  ANALYST
5   NaN   NaN        8  TESTING

#Feature Engineering:

In [ ]:
df=pd.read_csv("Titanic-Dataset.csv")
df.head()

df["family_count"]=df["SibSp"]+df["Parch"]+1
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,family_count
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [ ]:
df["Surname"]=[i.split(',')[0] for i in df["Name"]]
df.head()

df["FirstName"]=[i.split(",")[1].split(".")[1].split()[0] for i in df["Name"]]
df.head()

df["Alone"]=(df["family_count"]==1).astype(bool)
df.head()

# df['Age_group'] = ['Teenager' if Age < 20 else 'Middle Aged' if Age <= 50 else 'Old' for Age in df['Age']]

df["Age_Group"]=np.where(df["Age"]<20,"Teenager",np.where(df["Age"]<50,"Middle Age","old"))

df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,family_count,Surname,FirstName,Alone,Age_Group
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,Braund,Owen,False,Middle Age
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,Cumings,John,False,Middle Age
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,Heikkinen,Laina,True,Middle Age
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,Futrelle,Jacques,False,Middle Age
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,Allen,William,True,Middle Age

In [ ]:
df2=pd.read_csv("amazon_fires (2).csv",encoding="ISO-8859-1")

df2["date"]=[i.split('/')[1] for i in df2["encontro"] ]



# df2["mes1"]=df2["mes"][0:3:1]
# df2.head()

# df2["mes1"]=[i[0:3:1] for i in df2["mes"]]
# df2.head()

df2['mes1']= [i[:3] for i in df2['mes']]
df2.head()

    ano      mes estado   numero  encontro date mes1
0  1998  Janeiro   Acre  0 Fires  1/1/1998    1  Jan
1  1999  Janeiro   Acre  0 Fires  1/1/1999    1  Jan
2  2000  Janeiro   Acre  0 Fires  1/1/2000    1  Jan
3  2001  Janeiro   Acre  0 Fires  1/1/2001    1  Jan
4  2002  Janeiro   Acre  0 Fires  1/1/2002    1  Jan

#Pivot Table:

In [ ]:
df=pd.read_csv("Titanic-Dataset (1).csv")
print(df.head())
df.pivot_table(values=["Age"],index="Sex")

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

              Age
Sex
female  27.915709
male    30.726645

In [ ]:
df2=pd.read_csv("https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/hr_data.csv")
df2.head()

df2['salary'] = df2['salary'].replace("low", 20000)
df2['salary'] = df2['salary'].replace("medium",40000)
df2['salary'] = df2['salary'].replace("high", 40000)
df2

type(df2["salary"][0])
df2.head()

pivot=df2.pivot_table(values=["salary"],index="department",aggfunc=np.sum)
pivot
pivot.sort_values(by="salary")

<ipython-input-204-6a8adcc4339c>:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['salary'] = df2['salary'].replace("high", 40000)
<ipython-input-204-6a8adcc4339c>:12: FutureWarning: The provided callable <function sum at 0x7f95ddfcbce0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot=df2.pivot_table(values=["salary"],index="department",aggfunc=np.sum)

                salary
department
management    21600000
hr            22860000
accounting    23520000
RandD         24200000
marketing     26280000
product_mng   27060000
IT            36900000
support       66240000
technical     81360000
sales        123620000

#date_range():

In [ ]:
pd.date_range(start='01/01/2024',end='12/31/2024',freq="s")

DatetimeIndex(['2024-01-01 00:00:00', '2024-01-01 00:00:01',
               '2024-01-01 00:00:02', '2024-01-01 00:00:03',
               '2024-01-01 00:00:04', '2024-01-01 00:00:05',
               '2024-01-01 00:00:06', '2024-01-01 00:00:07',
               '2024-01-01 00:00:08', '2024-01-01 00:00:09',
               ...
               '2024-12-30 23:59:51', '2024-12-30 23:59:52',
               '2024-12-30 23:59:53', '2024-12-30 23:59:54',
               '2024-12-30 23:59:55', '2024-12-30 23:59:56',
               '2024-12-30 23:59:57', '2024-12-30 23:59:58',
               '2024-12-30 23:59:59', '2024-12-31 00:00:00'],
              dtype='datetime64[ns]', length=31536001, freq='s')

In [ ]:
data={"Date":['2022-01-01','2022-01-02',"2022-01-03","2022-01-04","2022-01-05"],"sales":[100,200,300,400,500]}
df=pd.DataFrame(data)
print(df)
df["Date"]=pd.to_datetime(df["Date"])

range=pd.date_range('2022-01-01','2022-01-03')

pivot=pd.pivot_table(df[df["Date"].isin(range)],values="sales",index="Date")

pivot

         Date  sales
0  2022-01-01    100
1  2022-01-02    200
2  2022-01-03    300
3  2022-01-04    400
4  2022-01-05    500

            sales
Date
2022-01-01  100.0
2022-01-02  200.0
2022-01-03  300.0

#to_datetime():

In [ ]:
df=pd.read_csv("amazon_fires (2).csv",encoding="ISO-8859-1")
df.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [1]:
import pandas as pd

# Creating a DataFrame
df1 = pd.DataFrame({"Year": [2024, 2023, 2022, 2021],
                     "Month": [12, 2, 11, 8],
                     "Day": [7, 14, 15, 20]})

# Converting Year, Month, and Day columns into a datetime format
dt = pd.to_datetime(df1[['Year', 'Month', 'Day']])

# Checking the type of a specific datetime value
print(type(dt.iloc[1]))  # Use .iloc instead of indexing with []

# Converting a string date into datetime
s = "20240829"
s1 = pd.to_datetime(s, format="%Y%m%d")
print(type(s1))  # This will print <class 'pandas._libs.tslibs.timestamps.Timestamp'>

# Creating another DataFrame (assuming df exists)
df = pd.DataFrame({"encontro": ["2024-08-29", "2023-07-15", "2022-11-10"]})

# Converting the 'encontro' column to datetime format
df["encontro"] = pd.to_datetime(df["encontro"])

# Extracting the day from each date in the 'encontro' column
out = df["encontro"].dt.day

print(out)

<class 'pandas._libs.tslibs.timestamps.Timestamp'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
0    29
1    15
2    10
Name: encontro, dtype: int32

#Feature Engineering Task:

In [ ]:
d1={"Name":["Iron Man","Captain America","Hulk","Black Panter","SpiderMan","Venom","Vision","Thor","Loki","AntMan"],"Maths":[95,90,95,82,85,90,85,86,87,88],"Physics":[90,95,85,80,75,80,85,90,95,80],"Chemistry":[85,89,88,90,95,95,96,97,85,90],"Biology":[90,95,85,87,89,88,85,88,89,90],"Geography":[80,85,89,90,95,97,80,85,90,95]}
df=pd.DataFrame(d1)
df["Per"]=(df["Maths"]+df["Physics"]+df["Chemistry"]+df["Biology"]+df["Geography"])/5
df
Grade=[]

for i in df["Per"]:
  if i>100 or i<0:
    Grade.append("Invalid")
  elif 85<=i<=100:
    Grade.append("A+")
  elif 70<=i<=84.9:
    Grade.append("A")
  elif 50<=i<=69.9:
    Grade.append("B")
  elif 35<=i<=49.9:
    Grade.append("C")
  elif i<=34.9:
    Grade.append("Fail")

df["Grade"]=Grade

df

new_row=pd.DataFrame({"Name":["Mean"], "Maths":[df["Maths"].mean()], "Physics":[df["Physics"].mean()],"Chemistry":[df["Chemistry"].mean()],"Biology":[df["Biology"].mean()],"Geography":[df["Geography"].mean()],"Per":[df["Per"].mean()],"Grade":["WellDone"]})

df=pd.concat([df,new_row],ignore_index=True)

df

,Name,Maths,Physics,Chemistry,Biology,Geography,Per,Grade
0,Iron Man,95.0,90.0,85.0,90.0,80.0,88.0,A+
1,Captain America,90.0,95.0,89.0,95.0,85.0,90.8,A+
2,Hulk,95.0,85.0,88.0,85.0,89.0,88.4,A+
3,Black Panter,82.0,80.0,90.0,87.0,90.0,85.8,A+
4,SpiderMan,85.0,75.0,95.0,89.0,95.0,87.8,A+
5,Venom,90.0,80.0,95.0,88.0,97.0,90.0,A+
6,Vision,85.0,85.0,96.0,85.0,80.0,86.2,A+
7,Thor,86.0,90.0,97.0,88.0,85.0,89.2,A+
8,Loki,87.0,95.0,85.0,89.0,90.0,89.2,A+
9,AntMan,88.0,80.0,90.0,90.0,95.0,88.6,A+
10,Mean,88.3,85.5,91.0,88.6,88.6,88.4,WellDone

In [ ]:
df=pd.DataFrame({"Name":["Iron Man","Captain America","Spider Man"],"Age":[52,100,25]})
df

df2=pd.DataFrame({"Name":["Hulk"],"Age":[40]})

df=pd.concat([df,df2],ignore_index=True)